apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    user: bususer
    secureJsonData:
      password: buspassword
    jsonData:
      database: busdb
      sslmode: disable